'use client';

import "./styles/main.scss";
import { Footer } from "./components/footer/Footer";
import Header from "./components/Navbar/Header";
import GlobalProvider from "./context/global/Global-provider";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>E-Medica</title>
        <link rel="icon" href="/images/favicon.ico" sizes="any" />
        <link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet"></link>
        <script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
      </head>
      <body>
        <GlobalProvider>
          <Header />

          <main>{children}</main>

          <Footer />
        </GlobalProvider>
      </body>
    </html>
  );
};
export default RootLayout;
